### ISSUE TITLE
How to run it?

### ISSUE THREAD

**Issue by 4del-Yousefi** [VisionXLab/STAR-MMRotate#4]
Hello, I want to ask can we have few examples on how on to run  the code and get the graphs and so on?

**Comment by XZNWU** [comment]
I'd really like to know how you test and train the code you shared? Which config file is your network?

**Comment by yangxue0827** [comment]
STAR is a dataset that can be used for oriented object detection (OOD). MMrotate is a toolkit for ODD, which contains many classical methods. You can refer to the official [repo](https://github.com/open-mmlab/mmrotate) and [documentation](https://mmrotate.readthedocs.io/en/latest/) if you want to learn more.
