### ISSUE TITLE
HOD-Net

### ISSUE THREAD

**Issue by hias-lcj** [VisionXLab/STAR-MMRotate#7]
Hello,
In your recent paper "STAR: A First-Ever Dataset and A Large-Scale Benchmark for Scene Graph Generation in Large-Size Satellite Imagery," you mentioned the HOD-Net method for OBD which shows promising performance. I am interested in knowing if you plan to release the code for HOD-Net publicly.
thanks.

**Comment by yangxue0827** [comment]
It will be open source after the paper is accepted. Thank you for your patience.
